### PR TITLE
Bump GitHub action workflows

### PR DESCRIPTION
**Pull request by deining**
Currently , the deployment workflow fails, as seen [here](https://github.com/gin-gonic/website/actions/runs/8824558703).
This PR fixes that. It pulls in the latest version of docsy which now makes use of bootstrap 5. I removed most all of the few custom partial files except for `footer.html`. Site looks good to me. After deployment, please have a look whether google analytics is still working, not sure about this.

### CODE REVIEW

**Comment by KostLinux** [comment]
@appleboy could you merge it please?

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
@deining Thanks.

**Comment by appleboy** [comment]
image

Can't working.

**Comment by appleboy** [comment]
The home page is very strange. https://gin-gonic.com/

**Pull request merged**
