### PR TITLE
add user 

### PR DESCRIPTION
**Pull request by wenjianzhang**
go-admin

### CODE REVIEW

**Review by appleboy — APPROVED** [review]

**Comment by lawxen** [comment]
Why a commercial version framework be committed here,  The open source version is far inferior to its commercial version, Most users have to buy the commercial version to work well with it @appleboy

**Comment by appleboy** [comment]
@lawxen Thanks for your reminder. I will remove the `go-admin` project

**Comment by appleboy** [comment]
@lawxen Done here: https://github.com/gin-gonic/website/commit/bf286c8f40754b6019394119fcbe65dc7e0b012f

**Comment by lawxen** [comment]
Maybe we can add a commercial group tag to show those excellent product like go-admin

**Pull request merged**
