### PR TITLE
Deployment previews for pull requests

### PR DESCRIPTION
**Pull request by jasonbarry**
I think Gin-Gonic would benefit in having deployment previews on every pull request, that way we can generate an automatic build of the website per PR rather than having to checkout branches locally to review/verify changes.

These are the changes needed to integrate w/ [FeaturePeek](https://featurepeek.com), a deployment preview provider. If the GitHub App is installed (for webhooks), then every subsequent PR will have its own deployment preview.

### CODE REVIEW

**Comment by appleboy** [comment]
@thinkerou What do you think about this?

**Review by thinkerou — APPROVED** [review]

**Comment by thinkerou** [comment]
> @thinkerou What do you think about this?

merged, thanks!

**Comment by jasonbarry** [comment]
@appleboy @thinkerou that's great! Please be sure to install the [GitHub App](https://github.com/apps/featurepeek) on this repo (for webhooks) and for at least one person in the Gin-Gonic org to create a free [account](https://dashboard.featurepeek.com) on FeaturePeek – the automation will kick in then.

**Comment by thinkerou** [comment]
> @appleboy @thinkerou that's great! Please be sure to install the [GitHub App](https://github.com/apps/featurepeek) on this repo (for webhooks) and for at least one person in the Gin-Gonic org to create a free [account](https://dashboard.featurepeek.com) on FeaturePeek – the automation will kick in then.

done

**Pull request merged**
